### ISSUE TITLE
/api/login Errors on vercel edge middleware

### ISSUE THREAD

**Issue by luskin** [awinogrodzki/next-firebase-auth-edge#156]
When deployed to Vercel, the `/api/login` route throws the following error:

```
TypeError: Cannot read properties of undefined (reading 'split')
    at (../../node_modules/.pnpm/next-firebase-auth-edge@1.4.0_next@14.1.3/node_modules/next-firebase-auth-edge/lib/auth/rotating-credential.js:6:0)
    at (../../node_modules/.pnpm/next-firebase-auth-edge@1.4.0_next@14.1.3/node_modules/next-firebase-auth-edge/lib/auth/rotating-credential.js:19:0)
    at (../../node_modules/.pnpm/next-firebase-auth-edge@1.4.0_next@14.1.3/node_modules/next-firebase-auth-edge/lib/auth/cookies/sign.js:9:0)
    at (../../node_modules/.pnpm/next-firebase-auth-edge@1.4.0_next@14.1.3/node_modules/next-firebase-auth-edge/lib/next/cookies.js:61:0)
    at (../../node_modules/.pnpm/next-firebase-auth-edge@1.4.0_next@14.1.3/node_modules/next-firebase-auth-edge/lib/next/cookies.js:96:0)
    at (../../node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/adapter.js:157:0)
```

`middleware.ts`:
```ts
import { NextRequest } from 'next/server';
import { authMiddleware } from 'next-firebase-auth-edge';
import { firebaseAuthMiddleware } from './lib/auth/auth.middleware';

export async function middleware(request: NextRequest) {
  return authMiddleware(request, firebaseAuthMiddleware);
}

export const config = {
  matcher: ['/api/login', '/api/logout', '/', '/((?!_next|favicon.ico|api|.*\\.).*)'],
};
```

`./lib/auth/auth.middleware.ts`
```ts
import { AuthMiddlewareOptions } from 'next-firebase-auth-edge/lib/next/middleware';

export const firebaseAuthMiddleware: AuthMiddlewareOptions = {
  loginPath: '/api/login',
  logoutPath: '/api/logout',
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY as string,
  cookieName: 'auth-session',
  cookieSignatureKeys: [process.env.AUTH_SECRET as string],
  cookieSerializeOptions: {
    path: '/',
    httpOnly: true,
    secure: false, // Set this to true on HTTPS environments
    sameSite: 'lax' as const,
    maxAge: 60 * 60 * 60 * 24, // sixty days
  },
  serviceAccount: {
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID as string,
    clientEmail: process.env.NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL as string,
    privateKey: process.env.FIREBASE_PRIVATE_KEY as string,
  },
};
```

**Comment by awinogrodzki** [comment]
Hey @luskin,

Are you sure `process.env.AUTH_SECRET` is defined? 

`Cannot read properties of undefined (reading 'split')` happens when first element of  `cookieSignatureKeys` is `undefined`

**Comment by luskin** [comment]
Thanks for the speedy response @awinogrodzki. That was actually the first thing I checked and yes, it's defined. I only have a single cookie signature key where as in your example you have two, could that lead to a problem?

**Comment by luskin** [comment]
So this is interesting, changing the name of the env variable to `AUTH_SIGNATURE_SECRET_KEY` instead of `AUTH_SECRET` fixed the problem. Vercel does not explicitly list `AUTH_SECRET` as a reserved environment variable, but must be somehow affected.

This issue is resolved.

# Solution

For any others that encounter do not name your env variable `AUTH_SECRET` when using Vercel.

**Comment by awinogrodzki** [comment]
Awesome, thanks for posting the solution!

In `next-firebase-auth-edge@1.4.1` I released input validation for `cookieSignatureKeys`. It will help others to debug similar cases.

Now, in case empty value is provided to `cookieSignatureKeys` user will see this error:

`Expected cookieSignatureKeys to contain at least one signature key. Received: [null]`
