### ISSUE TITLE
Cloudflare Worker:  __dirname is not defined

### ISSUE THREAD

**Issue by JamesCullum** [awinogrodzki/next-firebase-auth-edge#192]
As this package appears to be the only Firebase Auth library that allows to create a custom token, I gave it a run on Cloudflare Worker runtime. Would be great if it could be compatible.

When trying to build, I get the following error:

```
service core:user:name-of-project: Uncaught ReferenceError: __dirname is not defined
    at null.<anonymous> (index.js:1792:34)
    at null.<anonymous> (index.js:1795:7) in
  node_modules/next/dist/compiled/ua-parser-js/ua-parser.js
    at null.<anonymous> (index.js:11:50) in __require
    at null.<anonymous> (index.js:1826:64) in
  node_modules/next/dist/server/web/spec-extension/user-agent.js
    at null.<anonymous> (index.js:11:50) in __require
    at null.<anonymous> (index.js:1878:28) in node_modules/next/server.js
    at null.<anonymous> (index.js:11:50) in __require
    at null.<anonymous> (index.js:8404:20) in
  node_modules/next-firebase-auth-edge/lib/next/middleware.js
    at null.<anonymous> (index.js:11:50) in __require
    at null.<anonymous> (index.js:8547:24) in node_modules/next-firebase-auth-edge/lib/index.js

```

**Comment by JamesCullum** [comment]
This is the same issue as described [here](https://github.com/awinogrodzki/next-firebase-auth-edge/issues/164), but I'm more responsive, so we can try again

**Comment by awinogrodzki** [comment]
Hey @JamesCullum!

I've merged your pull request into `canary` branch.

You can test your changes by upgrading to `1.5.4-canary.1`
