### ISSUE TITLE
/api/login return 500

### ISSUE THREAD

**Issue by AbdallaEmadEldinAbdalla** [awinogrodzki/next-firebase-auth-edge#195]
Hello guys i have installed this package and created the middle ware but whenever i try to call `/api/login` it returns 500 with this error message 
```js 
 Error [ERR_HTTP_HEADERS_SENT]: Cannot append headers after they are sent to the client
    at ServerResponse.appendHeader (node:_http_outgoing:689:11)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
digest: "1430949486"
```

here's my code snippet 
```ts
import { NextRequest, NextResponse } from "next/server";
import { authMiddleware, redirectToHome, redirectToLogin } from "next-firebase-auth-edge";
import { firebaseConfig, serverConfig } from "./firebase/config";

const PUBLIC_PATHS = ['/signup', '/signin', '/reset-password'];

export async function middleware(request: NextRequest) {
    return authMiddleware(request, {
        loginPath: "/api/login",
        logoutPath: "/api/logout",
        apiKey: firebaseConfig.apiKey,
        cookieName: serverConfig.cookieName,
        cookieSignatureKeys: serverConfig.cookieSignatureKeys,
        cookieSerializeOptions: serverConfig.cookieSerializeOptions,
        serviceAccount: serverConfig.serviceAccount,
        handleInvalidToken: async (reason) => {
            console.info('Missing or malformed credentials', { reason });

            return redirectToLogin(request, {
                path: '/signin',
                publicPaths: PUBLIC_PATHS
            });
        },
        handleError: async (error) => {
            console.error('Unhandled authentication error', { error });

            return redirectToLogin(request, {
                path: '/signin',
                publicPaths: PUBLIC_PATHS
            });
        },
        handleValidToken: async ({ token, decodedToken }, headers) => {
            // Authenticated user should not be able to access /login, /register and /reset-password routes
            if (PUBLIC_PATHS.includes(request.nextUrl.pathname)) {
                return redirectToHome(request);
            }

            return NextResponse.next({
                request: {
                    headers
                }
            });
        },
    });
}

export const config = {
    matcher: [
        '/((?!_next/static|_next/image|favicon.ico|api|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
        "/api/login",
        "/api/logout",
    ],
};
```

and here's a sample of `/api/login` request

```js
fetch("http://localhost:3000/api/login", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9",
    "authorization": "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjMzMDUxMThiZTBmNTZkYzA4NGE0NmExN2RiNzU1NjVkNzY4YmE2ZmUiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiQWJkYWxsYSBFbWFkIEVsZGluIiwiaHNJZCI6IjMzNDA4OTUxIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FyeWEtOWY5MGYiLCJhdWQiOiJhcnlhLTlmOTBmIiwiYXV0aF90aW1lIjoxNzE3NDIwNzYyLCJ1c2VyX2lkIjoiclBSNTlxODR0TlUyc200aVdTSlFqWU9pdVIyMiIsInN1YiI6InJQUjU5cTg0dE5VMnNtNGlXU0pRallPaXVSMjIiLCJpYXQiOjE3MTc0MjA3NjIsImV4cCI6MTcxNzQyNDM2MiwiZW1haWwiOiJhZW1hZGVsZGluQGFyeWEuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX251bWJlciI6Iis5NzE1NjEwOTgxNDUiLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImFwcGxlLmNvbSI6WyIwMDAxNTMuZmFmNDY0YmU5ZTc4NGI5MmI5MDdhMzY4NWIwNzEwYTMuMDgzMiJdLCJnb29nbGUuY29tIjpbIjEwNDE4NzExNzYwODU4Nzg1ODU0MCJdLCJlbWFpbCI6WyJhZW1hZGVsZGluQGFyeWEuY29tIl0sInBob25lIjpbIis5NzE1NjEwOTgxNDUiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.UvhcyFJ10rWudWfKbu1tmHaQtkYh9r47KkwAosGzm0zdCoNqbIxF9EP0U7Ua2Dd5vgc9XYGEFLYeSMKSZ21Y6EO_ATryrEygk6gMnDEy541OaURoyRos_d4ybEf0VW0u4JllntL5ox0ufaXqGs9GlZESP3AVroXF8EJVDHJgQyqIgEMzmWqsnRQsKF7XhIaZSylTqWGe61LcAdfdq96xzr5KHqgCt_b7qovteJC9cQY4q7SJOq7UfxgsfcX8D3yfOYXCFwblL3f-scqmf-YMCcl8UH65QQjTWA2kYLO8s5vD1-bKgdIZZIQ81GPNfBUEcIsxW90y1S7sOW0GtSPIKw",
    "sec-ch-ua": "\"Chromium\";v=\"125\", \"Not.A/Brand\";v=\"24\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin"
  },
  "referrer": "http://localhost:3000/signin?redirect=%2Fdashboard",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "include"
});
```

also i just got this in `/api/login` response

```html
<script id="__NEXT_DATA__" type="application/json">
            {
                "props": {
                    "pageProps": {
                        "statusCode": 500
                    }
                },
                "page": "/_error",
                "query": {
                },
                "buildId": "development",
                "isFallback": false,
                "err": {
                    "name": "TypeError",
                    "source": "edge-server",
                    "message": "\"pkcs8\" must be PKCS#8 formatted string",
                    "stack": "TypeError: \"pkcs8\" must be PKCS#8 formatted string\n    at importPKCS8 (webpack-internal:///(middleware)/./node_modules/jose/dist/browser/key/import.js:32:15)\n    at sign (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/auth/jwt/sign.js:8:46)\n    at ServiceAccountSigner.sign (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/auth/jwt/crypto-signer.js:16:32)\n    at eval (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/auth/token-generator.js:67:32)\n    at async getCustomIdAndRefreshTokens (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/auth/index.js:216:29)\n    at async setAuthCookies (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/next/cookies.js:84:32)\n    at async adapter (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:179:16)\n    at async (file:///Users/abdallaemad/Desktop/Work/crypto-shadcn/node_modules/next/dist/server/web/sandbox/sandbox.js:110:22)\n    at async runWithTaggedErrors (file:///Users/abdallaemad/Desktop/Work/crypto-shadcn/node_modules/next/dist/server/web/sandbox/sandbox.js:107:9)\n    at async DevServer.runMiddleware (file:///Users/abdallaemad/Desktop/Work/crypto-shadcn/node_modules/next/dist/server/next-server.js:1062:24)"
                },
                "gip": true,
                "scriptLoader": [
                ]
            }</script>
```

**Comment by AbdallaEmadEldinAbdalla** [comment]
@awinogrodzki please if you can help me with this issue

**Comment by Jacquesjh** [comment]
Did you solve this? I got this error today too
