### ISSUE TITLE
Problem to refresh token

### ISSUE THREAD

**Issue by kalkusa** [awinogrodzki/next-firebase-auth-edge#199]
From time to time, I'm getting into the problem with getting refresh token

```
Error: Problem getting a refresh token: {"error":{"code":400,"message":"INVALID_CUSTOM_TOKEN","errors":[{"message":"INVALID_CUSTOM_TOKEN","domain":"global","reason":"invalid"}]}}
    at customTokenToIdAndRefreshTokens (webpack-internal:///(middleware)/./node_modules/.pnpm/next-firebase-auth-edge@1.5.3_next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_/node_modules/next-firebase-auth-edge/lib/auth/index.js:54:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async setAuthCookies (webpack-internal:///(middleware)/./node_modules/.pnpm/next-firebase-auth-edge@1.5.3_next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_/node_modules/next-firebase-auth-edge/lib/next/cookies.js:84:32)
    at async adapter (webpack-internal:///(middleware)/./node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/esm/server/web/adapter.js:179:16)
    at async (file://E:\GitHub\myprojectname\node_modules\.pnpm\next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\web\sandbox\sandbox.js:110:22)
    at async runWithTaggedErrors (file://E:\GitHub\myprojectname\node_modules\.pnpm\next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\web\sandbox\sandbox.js:107:9)
    at async DevServer.runMiddleware (file://E:\GitHub\myprojectname\node_modules\.pnpm\next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\next-server.js:1062:24)
    at async DevServer.runMiddleware (file://E:\GitHub\myprojectname\node_modules\.pnpm\next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\dev\next-dev-server.js:268:28)
    at async NextNodeServer.handleCatchallMiddlewareRequest (file://E:\GitHub\myprojectname\node_modules\.pnpm\next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\next-server.js:324:26)
    at async DevServer.handleRequestImpl (file://E:\GitHub\myprojectname\node_modules\.pnpm\next@14.2.3_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\base-server.js:822:28)
```

My middleware is pretty much copy paste from example:

```
import { NextRequest, NextResponse } from "next/server";
import {
  authMiddleware,
  redirectToHome,
  redirectToLogin,
} from "next-firebase-auth-edge";
import { serverConfig, clientConfig } from "./consts/config";
import { Paths } from "./consts/paths";

const PUBLIC_PATHS = ["/auth/sign-in", "/auth/sign-up"];

export async function middleware(request: NextRequest) {
  return authMiddleware(request, {
    loginPath: "/api/login",
    logoutPath: "/api/logout",
    apiKey: clientConfig.apiKey,
    cookieName: serverConfig.cookieName,
    cookieSignatureKeys: serverConfig.cookieSignatureKeys,
    cookieSerializeOptions: serverConfig.cookieSerializeOptions,
    serviceAccount: serverConfig.serviceAccount,
    handleValidToken: async ({ token, decodedToken }, headers) => {
      console.info("Valid token received", { decodedToken });
      if (PUBLIC_PATHS.includes(request.nextUrl.pathname)) {
        return redirectToHome(request);
      }

      return NextResponse.next({
        request: {
          headers,
        },
      });
    },
    handleInvalidToken: async (reason) => {
      console.info("Missing or malformed credentials", { reason });

      return redirectToLogin(request, {
        path: Paths.signIn,
        publicPaths: PUBLIC_PATHS,
      });
    },
    handleError: async (error) => {
      console.error("Unhandled authentication error", { error });

      return redirectToLogin(request, {
        path: Paths.signIn,
        publicPaths: PUBLIC_PATHS,
      });
    },
  });
}

export const config = {
  matcher: [
    "/api/login",
    "/api/logout",
    "/",
    "/((?!_next|favicon.ico|api|.*\\.).*)",
  ],
};
```

I tried versions of the library:
"next-firebase-auth-edge": "^1.4.3"
and
"next-firebase-auth-edge": "^1.5.3"

The issue appears on localhost, but on irregular basis. When I can't login to particular user on localhost I still can on vercel deployed app. Usually issue disappear after some time, one, two hours.

Clearing page data doesn't help (clearing cookies alone also).

I tried also to get token with force refresh (true param):
```
const credential = await signInWithEmailAndPassword(
        getAuth(app),
        username,
        password
      );
const idToken = await credential.user.getIdToken(true);
```

It seems to be some heisenbug as the config works perfectly well most of the time.

**Comment by awinogrodzki** [comment]
Hey @kalkusa! 

Thanks for reporting. 

I assume the issue is happening when user is calling `/api/login` endpoint due to `setAuthCookies` call in the stack trace.

Problem is happening between generating custom token based on provided `idToken` [here](https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/src/auth/index.ts#L386-L389), and exchanging it for a set of custom idToken and refreshToken [here](https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/src/auth/index.ts#L393-L397)

You can see, that between those steps we are calling `debug logger function` with custom token: 

```tsx
    debug('Generated custom token based on provided idToken', {customToken});
```

How often is the issue happening?

Can you run middleware with `debug: true` and share debug logs around the issue?

**Comment by awinogrodzki** [comment]
Just FYI, there was very similar issue to yours: https://github.com/awinogrodzki/next-firebase-auth-edge/issues/31

The reason was incorrect time set on the server, causing Google to reject token due to suspicious/outdated `iat/exp` claims
