### ISSUE TITLE
[TypeError]: "pkcs8" must be PKCS#8 formatted string

### ISSUE THREAD

**Issue by creativeindustriesgroup** [awinogrodzki/next-firebase-auth-edge#205]
Hello, I'm trying to set this up for the first time and for somer Eason am getting an error to do with public keys. Not really sure what this relates too, if it is an issue with my specific setup/config or not? 

````
next-firebase-auth-edge: Handle request path: /api/login
   next-firebase-auth-edge: Handle authentication API route
  next-firebase-auth-edge: No public keys found in cache. Fetching public keys from Google...
         cryptoRuntime: WebCryptoAPI
   next-firebase-auth-edge: Public keys fetched
         responseHeaders: {
  age: '37',
  alt-svc: 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
  cache-control: 'public, max-age=19806, must-revalidate, no-transform',
  content-encoding: 'gzip',
  content-length: '1736',
  content-type: 'application/json; charset=UTF-8',
  date: 'Fri, 28 Jun 2024 17:05:02 GMT',
  expires: 'Fri, 28 Jun 2024 22:35:08 GMT',
  server: 'scaffolding on HTTPServer2',
  vary: 'Origin,X-Origin,Referer',
  x-content-type-options: 'nosniff',
  x-frame-options: 'SAMEORIGIN',
  x-xss-protection: '0'
}
         cryptoRuntime: WebCryptoAPI
 next-firebase-auth-edge: Public keys cached
         cacheKey: https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com
         expiresAt: 1719614145665
         cryptoRuntime: WebCryptoAPI
```
 
```
Error [TypeError]: "pkcs8" must be PKCS#8 formatted string
    at importPKCS8 (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/node_modules/jose/dist/browser/key/import.js:32:15)
    at sign (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/auth/jwt/sign.js:8:46)
    at ServiceAccountSigner.sign (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/auth/jwt/crypto-signer.js:16:32)
    at eval (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/auth/token-generator.js:67:32)
    at async getCustomIdAndRefreshTokens (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/auth/index.js:216:29)
    at async setAuthCookies (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/next/cookies.js:84:32)
    at async adapter (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:179:16)
    at async (file:///Users/joeberry/Documents/GitHub/playground/node_modules/next/dist/server/web/sandbox/sandbox.js:110:22)
    at async runWithTaggedErrors (file:///Users/joeberry/Documents/GitHub/playground/node_modules/next/dist/server/web/sandbox/sandbox.js:107:9)
    at async DevServer.runMiddleware (file:///Users/joeberry/Documents/GitHub/playground/node_modules/next/dist/server/next-server.js:1062:24)
 POST /api/login 404 in 4ms
```

**Comment by awinogrodzki** [comment]
Hey @creativeindustriesgroup!

Could you confirm that you're passing a correct `serviceAccount.privateKey` to `authMiddleware`?

Please remember to unescape new line characters if you're using private key copied from credential json file, as so:

```ts
    privateKey: process.env.FIREBASE_ADMIN_PRIVATE_KEY.replace(/\\n/g, "\n")
```

**Comment by creativeindustriesgroup** [comment]
Ah yes, apologies and thank you.
