### ISSUE TITLE
Problem getting a refresh token

### ISSUE THREAD

**Issue by fedetoledo** [awinogrodzki/next-firebase-auth-edge#226]
I'm having the following issue
``` 
⨯ Error: Problem getting a refresh token: {"error":{"code":400,"message":"INVALID_CUSTOM_TOKEN","errors":[{"message":"INVALID_CUSTOM_TOKEN","domain":"global","reason":"invalid"}]}}
    at customTokenToIdAndRefreshTokens (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/auth/index.js:54:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getCustomIdAndRefreshTokens (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/auth/index.js:231:36)
    at async setAuthCookies (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/next/cookies.js:132:26)
    at async adapter (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:179:16)
    at async (root/node_modules/next/dist/server/web/sandbox/sandbox.js:110:22)
    at async runWithTaggedErrors (root/node_modules/next/dist/server/web/sandbox/sandbox.js:107:9)
    at async DevServer.runMiddleware (root/node_modules/next/dist/server/next-server.js:1062:24)
    at async DevServer.runMiddleware (root/node_modules/next/dist/server/dev/next-dev-server.js:268:28)
    at async NextNodeServer.handleCatchallMiddlewareRequest (root/node_modules/next/dist/server/next-server.js:324:26)
 ○ Compiling /_error ...
 ✓ Compiled /_error in 1156ms (252 modules)
 GET /api/login 404 in 8ms
Missing or malformed credentials { reason: 'MISSING_CREDENTIALS' }
Missing or malformed credentials { reason: 'MISSING_CREDENTIALS' }
 ○ Compiling /login ...
 ✓ Compiled /login in 10.5s (1703 modules)
 ⨯ Error [ERR_HTTP_HEADERS_SENT]: Cannot append headers after they are sent to the client
    at ServerResponse.appendHeader (node:_http_outgoing:685:11)
    at AsyncLocalStorage.run (node:async_hooks:338:14)
digest: "3444842769"
```

The expiration time looks good. I read some of the issues here but nothing worked

**Comment by fedetoledo** [comment]
Hey @awinogrodzki!

Thanks for your quick response. Here's the full logs
```
ⓘ next-firebase-auth-edge: Handle request
	 path: /api/login
ⓘ next-firebase-auth-edge: Handle authentication API route
ⓘ next-firebase-auth-edge: No public keys found in cache. Fetching public keys from Google...
	 cryptoRuntime: WebCryptoAPI
ⓘ next-firebase-auth-edge: Public keys fetched
	 responseHeaders: {
  age: '52',
  alt-svc: 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
  cache-control: 'public, max-age=22349, must-revalidate, no-transform',
  content-encoding: 'gzip',
  content-length: '1553',
  content-type: 'application/json; charset=UTF-8',
  date: 'Wed, 07 Aug 2024 21:30:47 GMT',
  expires: 'Thu, 08 Aug 2024 03:43:16 GMT',
  server: 'scaffolding on HTTPServer2',
  vary: 'Origin,X-Origin,Referer',
  x-content-type-options: 'nosniff',
  x-frame-options: 'SAMEORIGIN',
  x-xss-protection: '0'
}
	 cryptoRuntime: WebCryptoAPI
ⓘ next-firebase-auth-edge: Public keys cached
	 cacheKey: https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com
	 expiresAt: 1723088648066
	 cryptoRuntime: WebCryptoAPI
ⓘ next-firebase-auth-edge: Generated custom token based on provided idToken
	 customToken: eyJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImlhdCI6MTcyMzA2NjI5OSwiZXhwIjoxNzIzMDY5ODk5LCJpc3MiOiJ0b2xlZG9mZWRlcmljbzExQGdtYWlsLmNvbSIsInN1YiI6InRvbGVkb2ZlZGVyaWNvMTFAZ21haWwuY29tIiwidWlkIjoiamlRTnhleW9wdlB3d2F2MmZ3Z2xHdG1YZ1g1MyIsImNsYWltcyI6eyJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInNvdXJjZV9zaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.DxA5Tdntj-QDUZ8l1lFL0my7QUtthQpuBw_ZkyaKeWQX6pt-U4qczoRy8jJp8GRQW2P-vEHtcs-uuAfvR_Ua6nxZ0yt5uGDTefQeuHzlerfcG4lZ2DThckAqrY_0LvVuVRBInnZi101sQn414yWAw8Ml8ZsHa06MdAuMjVaOxhNyHoPdBdHZbIQfDdm9Uh-KLmhrey6h4nGESJqo7v633_dIhjLJH2rAASJq-hHmrRxoB11xVdFG_NOPc-KQDcg0A1dtVRwGbi5o07T4_FopfDxMsr-gCNuSRIpqv-JqEYki4aooArtuaH0WTJdk9yniotqYbZ16VTdaJVQP6ghKyw
 ⨯ Error: Problem getting a refresh token: {"error":{"code":400,"message":"INVALID_CUSTOM_TOKEN","errors":[{"message":"INVALID_CUSTOM_TOKEN","domain":"global","reason":"invalid"}]}}
    at customTokenToIdAndRefreshTokens (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/auth/index.js:54:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getCustomIdAndRefreshTokens (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/auth/index.js:231:36)
    at async setAuthCookies (webpack-internal:///(middleware)/./node_modules/next-firebase-auth-edge/lib/next/cookies.js:132:26)
    at async adapter (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:179:16)
    at async (file:///Users/fedetoledo/Desktop/freelance/mira-precios/node_modules/next/dist/server/web/sandbox/sandbox.js:110:22)
    at async runWithTaggedErrors (file:///Users/fedetoledo/Desktop/freelance/mira-precios/node_modules/next/dist/server/web/sandbox/sandbox.js:107:9)
    at async DevServer.runMiddleware (file:///Users/fedetoledo/Desktop/freelance/mira-precios/node_modules/next/dist/server/next-server.js:1062:24)
    at async DevServer.runMiddleware (file:///Users/fedetoledo/Desktop/freelance/mira-precios/node_modules/next/dist/server/dev/next-dev-server.js:268:28)
    at async NextNodeServer.handleCatchallMiddlewareRequest (file:///Users/fedetoledo/Desktop/freelance/mira-precios/node_modules/next/dist/server/next-server.js:324:26)
 GET /api/login 404 in 3ms
 ⨯ Error [ERR_HTTP_HEADERS_SENT]: Cannot append headers after they are sent to the client
    at ServerResponse.appendHeader (node:_http_outgoing:685:11)
    at AsyncLocalStorage.run (node:async_hooks:338:14)
digest: "3444842769"
ⓘ next-firebase-auth-edge: Handle request
	 path: /
ⓘ next-firebase-auth-edge: Missing authentication cookies
ⓘ next-firebase-auth-edge: Token is missing or has incorrect formatting. This is expected and usually means that user has not yet logged in
	 reason: MISSING_CREDENTIALS
Missing or malformed credentials { reason: 'MISSING_CREDENTIALS' }
ⓘ next-firebase-auth-edge: Handle request
	 path: /login
ⓘ next-firebase-auth-edge: Missing authentication cookies
ⓘ next-firebase-auth-edge: Token is missing or has incorrect formatting. This is expected and usually means that user has not yet logged in
	 reason: MISSING_CREDENTIALS
Missing or malformed credentials { reason: 'MISSING_CREDENTIALS' }
```

**Comment by awinogrodzki** [comment]
Your custom token structure and dates seem to be correct.

When you look into [official docs](https://firebase.google.com/docs/reference/rest/auth) you can see that `INVALID_CUSTOM_TOKEN` can happen due to:

> The custom token format is incorrect or the token is invalid for some reason (e.g. expired, invalid signature etc.)

We ruled out _expired_ and _structure_, so most likely the signature is invalid.

Is there a chance that Firebase API key you are providing is assigned to different Firebase account?

To verify this, you can login to [Firebase Console](https://console.firebase.google.com/u/0/), select project with Project ID that matches value passed as `serviceAccount.projectId`, go to https://console.firebase.google.com/u/0/project/{{YOUR PROJECT ID}}/settings/general and see if `Web API key` matches the value provided as `API key`

**Comment by awinogrodzki** [comment]
Also @fedetoledo, 

Can you tell me in which timezone is your server located? I want to rule out time discrepancy

**Comment by fedetoledo** [comment]
I might have messed up the configuration. It's working now. Thanks for the help! 

Nice work!

**Comment by estraw1059** [comment]
@fedetoledo what did you mess up? I am running into the same issue.

**Comment by estraw1059** [comment]
Note if anyone else finds themself here I had the wrong service account email for my admin API Key.

**Comment by nolafs** [comment]
Well, I have been checking my configs and I cannot see where it could be wrong. I am still getting this error.

 Error: Problem getting a refresh token: {"error":{"code":400,"message":"INVALID_CUSTOM_TOKEN","errors":[{"message":"INVALID_CUSTOM_TOKEN","domain":"global","reason":"invalid"}]}}

**Comment by MW-Hochmann** [comment]
I had this issue and for me the issue at hand was that the time of my development machine was about 5 minutes ahead. After I corrected the time of my machine it worked.
