### ISSUE TITLE
InvalidCharacterError while authentication after deploying to Vercel

### ISSUE THREAD

**Issue by harshmathurx** [awinogrodzki/next-firebase-auth-edge#243]
The error is - 
```
InvalidCharacterError: atob() called with invalid base64-encoded data. (Only whitespace, '+', '/', alphanumeric ASCII, and up to two terminal '=' signs when the input data length is divisible by 4 are allowed.)
    at (node_modules/jose/dist/browser/runtime/asn1.js:61:35)
    at (node_modules/jose/dist/browser/runtime/asn1.js:119:11)
    at (node_modules/jose/dist/browser/key/import.js:22:11)
    at (node_modules/next-firebase-auth-edge/lib/auth/jwt/sign.js:8:46)
    at (node_modules/next-firebase-auth-edge/lib/auth/jwt/crypto-signer.js:16:32)
    at (node_modules/next-firebase-auth-edge/lib/auth/token-generator.js:67:31)
    at (node_modules/next-firebase-auth-edge/lib/auth/index.js:226:28)
    at (node_modules/next-firebase-auth-edge/lib/next/cookies.js:132:25)
    at (node_modules/next/dist/esm/server/web/adapter.js:157:15)
```

**Comment by harshmathurx** [comment]
Request Path - /api/login

**Comment by harshmathurx** [comment]
[GET] [middleware: "middleware"] /api/login reason=EDGE_FUNCTION_INVOCATION_FAILED, status=500, user_error=true

ⓘ next-firebase-auth-edge: No public keys found in cache. Fetching public keys from Google...

cryptoRuntime: WebCryptoAPI

InvalidCharacterError: atob() called with invalid base64-encoded data. (Only whitespace, '+', '/', alphanumeric ASCII, and up to two terminal '=' signs when the input data length is divisible by 4 are allowed.)

ⓘ next-firebase-auth-edge: Public keys fetched

 cacheKey: <LINK to cache key>

**Comment by harshmathurx** [comment]
@awinogrodzki can you please help here?

**Comment by awinogrodzki** [comment]
Hey @harshmathurx,

What version of `next-firebase-auth-edge` are you using?

Also, could you share the output of `npx next info` command?

**Comment by awinogrodzki** [comment]
@harshmathurx it looks like the value you provide as `serviceAccount.privateKey` is incorrectly formatted or there is an issue in `jose` library.

Could you verify that the value you provide as `serviceAccount.privateKey` is correct in Vercel?

If you are trying to setup `next-typescript-starter` or `next-typescript-minimal` example, make sure that `FIREBASE_ADMIN_PRIVATE_KEY` environment variable holds correct private key

**Comment by harshmathurx** [comment]
it does hold the right value. I am getting authenticated in local environment

**Comment by harshmathurx** [comment]
@awinogrodzki would you want access to the repo? to help me debug
