### ISSUE TITLE
Problem getting a refresh token: {"error":{"code":400,"message":"INVALID_CUSTOM_TOKEN","errors":[{"message":"INVALID_CUSTOM_TOKEN","domain":"global","reason":"invalid"}]}}

### ISSUE THREAD

**Issue by nolafs** [awinogrodzki/next-firebase-auth-edge#280]
Hi,

The minimal example does work for me but when integrate the starter version, I am hitting this wall. The custom token does not validate at all. 

![JWT](https://github.com/user-attachments/assets/9a30a5db-f41d-43c9-a793-fda318c39458)

```
Error: Problem getting a refresh token: {"error":{"code":400,"message":"INVALID_CUSTOM_TOKEN","errors":[{"message":"INVALID_CUSTOM_TOKEN","domain":"global","reason":"invalid"}]}}
    at customTokenToIdAndRefreshTokens (*****/.next/server/chunks/ssr/node_modules_next-firebase-auth-edge_lib_90f994._.js:1808:15)
    at async getCustomIdAndRefreshTokens (******.next/server/chunks/ssr/node_modules_next-firebase-auth-edge_lib_90f994._.js:2017:36)
    at async refreshCookiesWithIdToken (*****/.next/server/chunks/ssr/node_modules_next-firebase-auth-edge_lib_90f994._.js:3249:26)
    at async loginAction (/*****/.next/server/chunks/ssr/[root of the server]__db5186._.js:389:5)
```

Triple check my parameters, nothing seems to be wrong. Also setting  enableCustomToken: false, I was hoping to get around it at least but that does nothing. 

Thanks for your help.
Olaf

**Comment by nolafs** [comment]
Found the issue, seems the policy of the company's firebase project expires the services accounts. I had no knowledge about this that. Therefore my key was wrong.
