### ISSUE TITLE
Error: Component auth has not been registered yet

### ISSUE THREAD

**Issue by andreemic** [awinogrodzki/next-firebase-auth-edge#41]
I reinstalled npm deps and am now getting this error:

```
error - node_modules/firebase/node_modules/@firebase/component/dist/esm/index.esm2017.js (232:0) @ Provider.initialize
error - Error: Component auth has not been registered yet
    at eval (./services/firebase/index.ts:39:69)
    at (sc_client)/./services/firebase/index.ts (/Users/mikhailandreev/code/twitvid/twitvid-app/.next/server/app/(navbar)/create/page.js:6454:1)
    at __webpack_require__ (/Users/mikhailandreev/code/twitvid/twitvid-app/.next/server/webpack-runtime.js:33:43)
    at eval (./hooks/useUser.ts:9:82)
    at (sc_client)/./hooks/useUser.ts (/Users/mikhailandreev/code/twitvid/twitvid-app/.next/server/app/(navbar)/create/page.js:4947:1)
    at __webpack_require__ (/Users/mikhailandreev/code/twitvid/twitvid-app/.next/server/webpack-runtime.js:33:43)
    at eval (./providers/OnboardingProvider.tsx:9:72)
    at (sc_client)/./providers/OnboardingProvider.tsx (/Users/mikhailandreev/code/twitvid/twitvid-app/.next/server/app/(navbar)/create/page.js:6366:1)
    at __webpack_require__ (/Users/mikhailandreev/code/twitvid/twitvid-app/.next/server/webpack-runtime.js:33:43)
```

Since then I've reinstalled deps a couple times but the issue persists. In addition to the next-firebase-auth-edge files, my own Firebase file instantiates Firebase instances like this:
```
export const app = initializeApp(firebaseConfig);
export const getFirebaseAnalytics = async (): Promise<Analytics | null> =>
  await isSupported().then((yes) => (yes ? getAnalytics(app) : null));
export const auth = getAuth(app);

export const storage = getStorage(app);

export const functions = getFunctions(app, "europe-west3");
export const db = getFirestore(app);
```

Is this problematic? I understand that this might not be an issue with this framework at all... But if you have any idea let me know!

`npm ls @firebase/app` gives me
```
─┬ @stripe/firestore-stripe-payments@0.0.6
│ ├── @firebase/app@0.7.33
│ ├─┬ @firebase/auth@0.17.2
│ │ └── @firebase/app@0.7.33 deduped
│ └─┬ @firebase/firestore@3.10.1
│   └── @firebase/app@0.7.33 deduped
└─┬ firebase@9.20.0
  ├─┬ @firebase/analytics@0.9.5
  │ └── @firebase/app@0.7.33 deduped
  ├─┬ @firebase/app-check@0.6.5
  │ └── @firebase/app@0.7.33 deduped
  ├─┬ @firebase/app-compat@0.2.8
  │ └── @firebase/app@0.9.8
  ├── @firebase/app@0.9.8
  ├─┬ @firebase/auth-compat@0.4.0
  │ └─┬ @firebase/auth@0.23.0
  │   └── @firebase/app@0.7.33 deduped
  ├─┬ @firebase/auth@0.23.0
  │ └── @firebase/app@0.9.8 deduped
  ├─┬ @firebase/functions@0.9.4
  │ └── @firebase/app@0.7.33 deduped
  ├─┬ @firebase/installations@0.6.4
  │ └── @firebase/app@0.7.33 deduped
  ├─┬ @firebase/messaging@0.12.4
  │ └── @firebase/app@0.7.33 deduped
  ├─┬ @firebase/performance@0.6.4
  │ └── @firebase/app@0.7.33 deduped
  ├─┬ @firebase/remote-config@0.4.4
  │ └── @firebase/app@0.7.33 deduped
  └─┬ @firebase/storage@0.11.2
    └── @firebase/app@0.7.33 deduped

```

**Comment by awinogrodzki** [comment]
Thanks for reporting @andreemic

This error is connected with firebase failing to resolve it's dependencies. Could you copy your `package.json` contents? I'd like to know if you are installing `@firebase/*` packages explicitly.

Also, could you run `npm ls firebase` and post here the output?
