### ISSUE TITLE
cloudflare next-on-pages support

### ISSUE THREAD

**Issue by Enalmada** [awinogrodzki/next-firebase-auth-edge#69]
When deploying next.js on cloudflare pages [next-on-pages](https://github.com/cloudflare/next-on-pages), I get immediate 500 and this error in the authentication section of middleware from starter example:
```
TypeError: (intermediate value).default is not a function
    at k (xxpe9e4ms1j.js:363:55)
    at async w.runRouteMiddleware (xxpe9e4ms1j.js:515:13)
    at async w.checkRoute (xxpe9e4ms1j.js:554:69)
    at async w.checkPhase (xxpe9e4ms1j.js:579:15)
    at async w.run (xxpe9e4ms1j.js:603:13)
    at async G (xxpe9e4ms1j.js:612:10)
    at async z (xxpe9e4ms1j.js:608:50)
    at async jsonError (xxpe9e4ms1j.js:701:12) {
  stack: TypeError: (intermediate value).default is not a f…0)
    at async jsonError (xxpe9e4ms1j.js:701:12),
  message: (intermediate value).default is not a function
}
```

From what I can tell, firebase libraries just don't work well on cloudflare workers.  Putting this here as a warning for anyone else thinking of trying next-on-pages.
https://github.com/firebase/firebase-admin-node/issues/2069

There is a comment though in that thread:

> As a workaround, it is possible to interact with Firestore (and other Google APIs) from under Cloudflare Workers or Cloudflare Pages using Google's [REST API](https://firebase.google.com/docs/firestore/use-rest-api), for example:

```
import { Hono } from "hono"; // routing library for Cloudflare Workers
import { getAccessToken } from "web-auth-library/google"; // auth library for Cloudflare Workers

const app = new Hono();

app.get("/example", ({ env, executionCtx }) => {
  const accessToken = await getAccessToken({
    credentials: env.GOOGLE_CLOUD_CREDENTIALS, // GCP service account key (JSON)
    scope: "https://www.googleapis.com/auth/cloud-platform",
    waitUntil: executionCtx.waitUntil, // allows the token to be refreshed in the background
  });
  const prefixURL = `https://firestore.googleapis.com/v1/projects/${env.GOOGLE_CLOUD_PROJECT}/databases/(default)/documents`;
  const res = await fetch(`${prefixURL}/cities/LA`, {
    headers: { "Authorization": `Bearer ${accessToken}` }
  });
  ...
});
```
~ https://github.com/firebase/firebase-admin-node/issues/2069#issuecomment-1450824986

The suggested https://github.com/kriasoft/web-auth-library description:

> Authentication library for Google Cloud, Firebase, and other cloud providers that uses standard [Web Crypto API](https://developer.mozilla.org/docs/Web/API/Web_Crypto_API) and runs in different environments and runtimes, including but not limited to:
> 
> [Bun](https://bun.sh/)
> [Browsers](https://developer.mozilla.org/docs/Web/API/Web_Crypto_API)
> [Cloudflare Workers](https://workers.cloudflare.com/)
> [Deno](https://deno.land/)
> [Electron](https://www.electronjs.org/)
> [Node.js](https://nodejs.org/)
> [Vercel's Edge Runtime](https://edge-runtime.vercel.app/)

> It has minimum dependencies, small bundle size, and optimized for speed and performance.

Perhaps integrating with this web-auth-library could improve bundle size and performance of next-firebase-auth-edge and allow next.js apps using it to be deployed to provides beyond vercel.  It kinda looks like it might be a drop in replacement.  Thoughts?

**Comment by Enalmada** [comment]
Thanks @awinogrodzki for only this amazing library but for taking the time to do this upgrade.   Sorry for the delay in response, I was trying to work through some things before reporting back.  Unfortunately cloudflare next-on-pages is giving me other problems when trying to deploy:
* middleware matcher containing array causes 500 (can be worked around by making matcher a single string)
* https://env.t3.gg/ environment variables method doesn't show up client side (at least the way I am using it.  Can be worked around by directly using process.env)
* protected route throwing `ApolloError: The 'cache' field on 'RequestInitializerDict' is not implemented.` (researching)

I am going to close this since I believe all issues now are unrelated to next-firebase-auth-edge.  I am going to try [SST](https://docs.sst.dev/start/nextjs) and see if I have any better luck but I assume the changes to `jose` will only help there also.
